# Локальная разработка (не для прода):
#   docker compose -f docker-compose.dev.yml up --build -d

services:

  bot:
    build:
      context: .
      network: host
      args:
        PIP_INDEX_URL: https://mirrors.aliyun.com/pypi/simple/
    env_file:
      - .env
    container_name: support-bot
    command: sh -c "cd /usr/src/app && python -m app"
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - ./data/web_chat_images:/usr/src/app/data/web_chat_images
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    container_name: support-redis
    restart: always
    volumes:
      - ./redis/data/:/data
    networks:
      - network

networks:
  network:
